### ISSUE TITLE
Trampoline broken, or is it just me?

### ISSUE THREAD

**Issue by mrbackend** [elm-lang/trampoline#1]
Trying to learn how to use `Trampoline`, I just can't make it work stack-safely. Consider this simple example:

```
myLength : List a -> Int
myLength xs =
    Trampoline.evaluate (myLength_ xs)


myLength_ : List a -> Trampoline Int
myLength_ xs =
    case xs of
        h :: t ->
            Trampoline.jump (\() -> Trampoline.done (Trampoline.evaluate (myLength_ t) + 1))

        [] ->
            Trampoline.done 0
```

This turns out not to be stack safe, and the problem is that the call to `Trampoline.evaluate` inside the thunk is not in a tail position. I can't get my head around to rewrite `myLength` in a way that avoids the problem.

Then, I tried to make my own implementation based on https://gist.github.com/kevinmeredith/9798105 (in Scala), which explains the exact same problem I'm experiencing - and its solution - but then I run into a problem with the Elm type system, as Elm doesn't have anything like Scala's `Any`.

Now, I know that trampolines are inherently hard to use, and that I should avoid them if I can, but still I'm wondering: If I'm right that the current `Trampoline` is broken, is it at all possible to write a correct one in Elm?

**Comment by evancz** [comment]
In general, questions like this will do better on elm-discuss or http://www.reddit.com/r/elm.

The implementation is not broken. It's just that the helper function is not actually tail recursive in your example.


## Best Way

Elm has tail-call elimination for self-recursion, so you can just write this normally:

```elm
myLength : List a -> Int
myLength list =
  myLengthHelp 0 list

myLengthHelp : Int -> List a -> Int
myLengthHelp total list =
  case list of
    [] ->
      total

    _ :: rest ->
      myLengthHelp (total + 1) rest
```

Notice that I've reformulated `myLengthHelp` such that everything ends with a tail call or result.


## Trampoline Way

If you really want to use `Trampoline`, the important thing is that the helper function is tail recursive. So you can say something like this:

```elm
myLength : List a -> Int
myLength list =
    Trampoline.evaluate (myLengthHelp 0 list)

myLengthHelp : Int -> List a -> Trampoline Int
myLengthHelp total xs =
    case xs of
        _ :: rest ->
            Trampoline.jump (\() -> myLengthHelp (total + 1) rest))

        [] ->
            Trampoline.done total
```

This will be slower than the first version I gave because it is emulating the optimization that Elm already does.

Point is, if you call `evaluate` within a `jump`, you stepping down one stack frame. So if you do that a bunch, you keep adding new stack frames. I'm not saying never do it, but do it with care.
